[language_servers.pylsp]
enable_flake8 = false
enable_ruff = true
enable_mypy = true
enable_pylint = false
enable_pyflakes = false
enable_pydocstyle = false
enabled = true

[language_servers.ty]

[language_servers.basedpyright]

[ai]
rules = ""
mode = "manual"

[experimental]

[display]
default_table_max_columns = 50
default_width = "medium"
dataframes = "rich"
theme = "light"
reference_highlighting = false
default_table_page_size = 10
cell_output = "above"
code_editor_font_size = 14

[server]
follow_symlink = false
browser = "default"

[snippets]
custom_paths = []
include_default_snippets = true

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[package_management]
manager = "pip"

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[completion]
activate_on_typing = true
copilot = false

[formatting]
line_length = 79

[runtime]
std_stream_max_bytes = 1000000
default_auto_download = []
watcher_on_save = "lazy"
on_cell_change = "lazy"
reactive_tests = true
auto_instantiate = true
output_max_bytes = 8000000
default_sql_output = "auto"
auto_reload = "off"

[diagnostics]
